# ================================
# FILE: docker-compose.yml (ROOT DIRECTORY)
# ================================
version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: blockchain_postgres
    environment:
      POSTGRES_USER: riot
      POSTGRES_PASSWORD: riot9334
      POSTGRES_DB: blockchain_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blockchain_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: blockchain_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - blockchain_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bitcoin-node:
    image: btcpayserver/bitcoin:24.0
    container_name: blockchain_bitcoin
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - bitcoin_data:/data
    environment:
      BITCOIN_NETWORK: testnet
    command: >
      bitcoind
      -server=1
      -rpcuser=bitcoinrpc
      -rpcpassword=changeme123
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -txindex=1
      -testnet=1
    networks:
      - blockchain_network

  ethereum-node:
    image: ethereum/client-go:v1.13.5
    container_name: blockchain_ethereum
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ethereum_data:/root/.ethereum
    command:
      - --sepolia
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,txpool
      - --ws.origins=*
    networks:
      - blockchain_network

volumes:
  postgres_data:
  redis_data:
  bitcoin_data:
  ethereum_data:

networks:
  blockchain_network:
    driver: bridge

